# Generated by Django 6.1.1 on 2026-10-06 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Файл .glb. Держите до ~5 МБ — тяжёлые модели сначала сожмите.', upload_to='products/3d/', validators=[django.core.validators.FileExtensionValidator(['glb'])], verbose_name='3D-модель'),
        ),
    ]
